### ISSUE TITLE
requires 'fnv' library which isn't in gemspec

### ISSUE THREAD

**Issue by mepatterson** [pawandubey/cuckoo_filter#1]
`require "fnv"` throws an exception since that library isn't specified anywhere in the gem

**Comment by mepatterson** [comment]
actually, just realized its mentioned in the Gemfile... but that should really be in the gemspec, or else it won't work properly in certain contexts (like mine).

**Comment by pawandubey** [comment]
That's interesting. Gemspec should only contain development dependencies, but can you tell me more about your context and why it's not being required? It'll help me understand the issue better.

**Comment by mepatterson** [comment]
Added to a Rails app, the fnv gem never gets loaded and an exception gets
thrown by the require. Isn't it generally better to use a runtime
dependency in the gemspec?

http://guides.rubygems.org/patterns/#declaring-dependencies

**Comment by pawandubey** [comment]
@mepatterson thanks for pointing out this issue! I have pushed out a new release and updating the gem should fix things for you. Let me know if it does so that I can close this issue.
