### ISSUE TITLE
Serialize / deserialize a filter

### ISSUE THREAD

**Issue by DanielHeath** [pawandubey/cuckoo_filter#2]
I'm working on shrinking the (11gb zipped) 'have I been pwned' password breach dataset into a cuckoo filter, so a webapp can efficiently check whether a new password has previously been disclosed.

It would be useful to be able to use this to 'pre-bake' a filter file.

**Comment by DanielHeath** [comment]
Nevermind, `Marshal.dump` and `Marshal.load` work fine.

**Comment by pawandubey** [comment]
@DanielHeath I'm assuming this issue can be closed. Feel free to reopen if required.

P.S: did you get your project working?

**Comment by DanielHeath** [comment]
Ended up writing my own pure-ruby bloom filter (~40 loc). 

The array approach used in this library is much too slow for the kind of load I'm using - instead, I created a string with the 8bit-ascii encoding and treated it as a bitfield.

**Comment by DanielHeath** [comment]
Also, serializing an 8bit-ascii string to a binary file is (obviously) trivial and has no encoding/decoding overhead.

**Comment by pawandubey** [comment]
That's a neat hack! Thanks for the update 🙌
